{
 "title": "Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Currency", "label": "Currency", "query": "₹,€,$,¥,₩,£,฿" },
   {
    "name": "Price",
    "label": "Air Costs  per m³",
    "query": "0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.50, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.60, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.70, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.00"
   },
   { "name": "EnergyAir", "label": "Energy per m³ [kWh/m³]", "query": "0.01" },
   { "name": "CO2Energy", "label": "CO2 per Energy [kg/kWh]", "query": "0.4" },
   {
    "name": "AirConversionFactor",
    "label": "Flow Rate Unit",
    "query": "m³/h : 1,cfm : 0.58857777, l/min : 16.6666667"
   },
   { "name": "MaxVolume", "label": "Max m³ per hour", "query": "2.16" },
   { "name": "MaxVolumeMin", "label": "Max m³ per min", "query": "0.036" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM VM-CD-C1-d",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "options": { "content": "&nbsp;\r\n# Consum de aer" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consum aer pe ora / ultime 24h",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "yaxes": [
    { "format": "litreh", "label": "m3" }
   ],
   "targets": [
    {
     "alias": "Consum aer pe ora",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AirVolume",
     "query": "SELECT non_negative_difference(last(\"Volume\")) AS \"Air consumption\" FROM \"AF2\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "Volume" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Air consumption" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "demo_Volume" }
     ]
    }
   ]
  },
  {
   "title": "Consum aer pe zi / ultime 14 zile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "locale", "label": "m3" }
   ],
   "targets": [
    {
     "alias": "Hourly Air Consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AirVolume",
     "query": "SELECT non_negative_difference(last(\"Volume\")) AS \"Air consumption\" FROM \"AF2\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "Volume" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Air consumption" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "demo_Volume" }
     ]
    }
   ]
  },
  {
   "title": "Monitorizare cilindri",
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 31 },
   "options": {
    "content": "&nbsp;\r\n# Monitorizarea cilindrilor"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timp de ciclu complet al cilindrilor",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"min\" AS \"Min [ms]\", \"max\" AS \"Max [ms]\", last(\"payload\") AS \"Current [ms]\", \"statusVal\" AS \"Status\" FROM \"CylinderCycleTime\" GROUP BY \"topic\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "&nbsp;\r\n# Monitorizarea valvelor"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monitorizare valve",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"max\") AS \"Life Time\", last(\"wear\") AS \"%\", last(\"payload\") AS \"Current\", last(\"statusVal\") AS \"Status\" FROM  \"ValveCounter\"GROUP BY \"topic\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}